format: "[&6%prefix&r] &3%name&7:&r %message"
users:
    Player:
        permissions:
            permissions.example: true
        groups:
        - admin
groups:
    default:
        permissions:
            permissions.build: false
    admin:
        permissions:
            permissions.reload: true
        inheritance:
        - default
