name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}

commands:
  permissions:
    description: Commands for manipulating permissions.
    usage: |
        /<command> reload - reload the configuration from disk.

permissions:
  permissions.reload:
    description: Allows use of /permissions reload.
    default: op
